# Generated by Django 5.0.4 on 2024-06-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0002_imagefeed_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefeed',
            name='graph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
